#!/bin/bash
#
#	/etc/rc.d/init.d/stunnel
#
# Starts the stunnel daemon

# Source function library.
# chkconfig: 345 98 20
# description: stunnel
# processname: stunnel

. /etc/rc.d/init.d/functions

RETVAL=0

start() {
	echo -n $"Starting stunnel daemon: "	
  cd /;
  /usr/bin/stunnel >> /var/log/stunnel.log 2>&1 </dev/null &
  RETVAL=$?
  disown 
  [ $RETVAL -ne 0 ] && failure
	[ $RETVAL -eq 0 ] && success
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping stunnel daemon: "
  pkill -f /usr/bin/stunnel;
  RETVAL=$?
  [ $RETVAL -ne 0 ] && failure
	[ $RETVAL -eq 0 ] && success
  echo
  return $RETVAL
}

restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
esac

exit $RETVAL
