shell = "zsh"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.fzf]
github = 'junegunn/fzf'
apply = ['fzf-install', 'fzf-source']

[plugins.evalcache]
github = 'mroth/evalcache'
apply = ['source']

#================
# defer loading
#================
[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.zsh-autosuggestions.hooks]
post = "export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'"

[plugins.zsh-abbr]
github = 'olets/zsh-abbr'

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.fast-syntax-highlighting.hooks]
post = "test -e ~/.cache/fsh/current_theme.zsh || fast-theme -q ~/.config/fsh/solarized.ini --secondary=zdharma"

#================
# eval cache
#================
[plugins.starship]
inline = '_evalcache starship init zsh'

[plugins.zoxide]
inline = '_evalcache zoxide init zsh'

[plugins.mise]
inline = '_evalcache mise activate zsh'

[plugins.direnv]
inline = '_evalcache direnv hook zsh'

[plugins.kubectl-completion]
inline = '_evalcache kubectl completion zsh'

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH == *{{ dir }}* ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"
