format = '$all'
command_timeout = 1000

[directory]
style = "blue"
truncate_to_repo = false
truncation_symbol = '.../'

[username]
show_always = false

[character]
success_symbol = "[\\$]()"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-purple"

[git_status]
disabled = true
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

## disabled
[python]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[perl]
disabled = true

[docker_context]
disabled = true

[kotlin]
disabled = true

[package]
disabled = true

[aws]
disabled = true
