"$schema" = 'https://starship.rs/config-schema.json'

format = """$line_break\
$all\
$time\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character\
"""

command_timeout = 1000

[fill]
symbol = ' '

[directory]
style = "blue"
truncate_to_repo = true
truncation_symbol = '.../'

[username]
show_always = false

[character]
success_symbol = "[\\$]()"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-purple"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "purple"

[git_metrics]
disabled = false
ignore_submodules = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%Y-%m-%d %T'
style = "cyan"

[shlvl]
disabled = false
symbol = '> '

[git_commit]
tag_symbol = " tag "
only_detached = false
#style = "bright-purple"

[git_status]
disabled = true
#ahead = ">"
#behind = "<"
#diverged = "<>"
#renamed = "r"
#deleted = "x"

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

#================
# disabled
#================
[python]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[perl]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[kotlin]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[status]
disabled = true

[battery]
disabled = true

[lua]
disabled = true
