"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden    = true

[opener]
vscode = [
	{ run = 'code "$@"', desc = 'VSCode', block = true },
]

[open]
rules = [
	# Folder
	{ name = "*/", use = [ "edit", "open", "vscode", "reveal" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "vscode", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "vscode", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "vscode", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "vscode", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "vscode", "reveal" ] },
	# Fallback
	{ name = "*", use = [ "open", "vscode", "reveal" ] },
]


