---
name: test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate shell script syntax
        run: bash -n bin/*.sh

      - name: Run install script
        run: ./bin/mkworld.sh

      - name: Load .zshrc
        run: |
          echo $TERM;
          echo $TERMINFO;
          ls /usr/lib/terminfo/x;
          zsh ~/.zshrc 2> ./error.log; cat error.log
          if [ -s error.log ]; then false; fi
